CREATE TABLE TABLE_1 (COLUMN_1 NUMBER);
CREATE TABLE TABLE_2 (COLUMN_2 NUMBER);

INSERT INTO TABLE_1 VALUES(1);
INSERT INTO TABLE_1 VALUES(1);
INSERT INTO TABLE_1 VALUES(0);
INSERT INTO TABLE_1 VALUES(0);
INSERT INTO TABLE_1 VALUES(2);
INSERT INTO TABLE_1 VALUES(3);
INSERT INTO TABLE_1 VALUES(NULL);
INSERT INTO TABLE_1 VALUES(NULL);

INSERT INTO TABLE_2 VALUES(1);
INSERT INTO TABLE_2 VALUES(1);
INSERT INTO TABLE_2 VALUES(0);
INSERT INTO TABLE_2 VALUES(2);
INSERT INTO TABLE_2 VALUES(4);
INSERT INTO TABLE_2 VALUES(NULL);
INSERT INTO TABLE_2 VALUES(NULL);
INSERT INTO TABLE_2 VALUES(NULL);

COMMIT;